Revert svn commits 674447 and 674525 as this causes a integration test case failure in the IBM JDK5/6
-------------------------------------------------------------------------------
Test set: org.apache.axis2.rpc.complex.ComplexDataTypesComplexDataTypesSOAP11Test
-------------------------------------------------------------------------------
Tests run: 37, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 81.149 sec <<< FAILURE!
testretDateTime(org.apache.axis2.rpc.complex.ComplexDataTypesComplexDataTypesSOAP11Test) Time elapsed: 2.034 sec <<< FAILURE!
junit.framework.ComparisonFailure: null expected:<2008-07-08T1[4]:31:44.551Z> but was:<2008-07-08T1[5]:31:44.551Z>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at 
org.apache.axis2.rpc.complex.ComplexDataTypesComplexDataTypesSOAP11Test.testretDateTime(ComplexDataTypesComplexDataTypesSOAP11Test.java:359)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:599)

674447 - there are instances where when we format the date it gives the wrong date, this commit is to fix the issue 
674525 - it is enough to set the DST_TIME to zero 

Amila, Deepal,

Can you please submit a JIRA / test case then we can work on making sure the issue is fixed across all JDK's.

thanks,
dims